### ISSUE TITLE
Issue with Types when stitching schema

### ISSUE THREAD

**Issue by tvvignesh** [gmac/schema-stitching-demos#1]
Hi. I tried doing `fetchRemoteSDL` and retrieving the SDL from the remote service instead of doing introspection as mentioned here: https://github.com/gmac/schema-stitching-demos/blob/master/01-combining-local-and-remote-schemas/index.js#L30 and it worked well.

But there was a typings issue as below:

<img width="542" alt="1" src="https://user-images.githubusercontent.com/1165845/100443435-b9e3a700-30cf-11eb-8f3c-0fc700890925.png">

where the object is nothing but same as in the example:

```ts
return {
    schema: buildSchema(remoteSchema),
    executor: httpExecutor
  };
```

Currently, working around this by adding a `ts-ignore` like this:

```ts
subschemas: [
      // @ts-ignore
      {
        schema: authService.schema,
        executor: authService.executor
      }
]
```

Thanks.

**CC:** @gmac

**Comment by gmac** [comment]
I guess I don’t follow the problem here. Looks like you haven’t converted the example into typescript, which I assume you are using? These examples are plain JavaScript. You’d need to add casting information as appropriate to your version of TypeScript. I’m intentionally using JavaScript as a lowest-common denominator.

Please let me know if I’m missing something else here that is technically inaccurate in the example.

**Comment by tvvignesh** [comment]
@gmac Thanks for the clarification. I assumed that it was compatible with Typescript out of the box. Will fix it on my end then 👍

**Comment by tvvignesh** [comment]
@gmac Btw, I just had to mark the return type as `AsyncExecutor` and the error above went away 🎉

```ts
import { AsyncExecutor } from '@graphql-tools/delegate';

const makeRemoteExecutor = function(url:string) : AsyncExecutor {
  return async ({ document, variables }) => {
    const query = typeof document === 'string' ? document : print(document);
    const fetchResult = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        query, variables
      })
    });
    return fetchResult.json();
  };
};
```

**Comment by gmac** [comment]
Sounds about right! Is Stitching starting to make more sense now with some concrete examples? I personally find it to be fairly intuitive given that the subservices are all plain GraphQL, versus Federation where there’s a bunch of magic happening at every layer of the stack to bring it all together.

**Comment by tvvignesh** [comment]
@gmac Stitching - Yes, Typemerging - In Progress . While I understood the concepts properly with both of ur help and have it setup as part of the stack, I am working to see how I can fit it for my usecases. Will share my progress as I go along.
