### ISSUE TITLE
NestJS support

### ISSUE THREAD

**Issue by XBeg9** [gmac/schema-stitching-demos#15]
Me and @dimatill working on [NestJS](https://docs.nestjs.com/graphql/quick-start) integration right now. Is it something that you are interested to add here as an example?

Btw, we are trying to get custom directives into the sdl, having some troubles. trying this approach with no luck: subservice-languages/javascript/services/products/schema.ts

**Comment by yaacovCR** [comment]
That sounds great to me! Although I am not so familiar with nest js, if you give me a code sample with where you are so far, and what is not working, I can try to offer some comments...

**Comment by yaacovCR** [comment]
Does nest is support directives or extensions btw? I would assume they support directives within schema first approach... Which approach were you trying? And does nest js let you pass in a standard graphqlschema, ie the product of stitchSchemas? Those are seemingly the two integration requirements....

**Comment by XBeg9** [comment]
@yaacovCR thanks for the quick feedback, we were able to run SDL + Schema Stitching with NestJS framework (code-first approach). I am trying to test it out e2e.

**Comment by XBeg9** [comment]
@yaacovCR everything looks great so far, I've made some e2e tests, SDL directives approach works as expected. 

Please give us some time to prepare the PR for NestJS handbook. We have it done using lerna + typescript + code-first approach, don't you mind if I will publish it as it is, or do want it to be converted to anything else?

Thanks

**Comment by yaacovCR** [comment]
Will leave that to @gmac :)

**Comment by gmac** [comment]
Thanks @XBeg9. Open the PR and we can see where it fits. If it can be expressed using a single subservice, just converting the last SDL setup in the JavaScript language example makes sense. If not, maybe we’ll start organizing into framework implementations.

**Comment by gmac** [comment]
Looking forward to a PR. Thanks!
