### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by orefalo** [gmac/schema-stitching-demos#18]
Greg & Yaacov,

Not an issue, just a big **thank you** for putting together and maintaining all these examples.
It helps a lot to understand the capabilities, tech and differences with federation.

Sincerely

**Comment by yaacovCR** [comment]
Yes I am basically an enthusiastic bystander here, a huge thanks to @gmac !

**Comment by gmac** [comment]
Thanks @orefalo!! Pleasure to do it, and I hope you’ll join us in this camp!

**Comment by orefalo** [comment]
If I may, 

You can simplify the startup process with **wait-on**
ie.
```
{
  "name": "combining-local-and-remote-schemas",
  "version": "0.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "tsc && copyfiles -u 1 src/services/products/*.graphql src/services/storefronts/*.graphql dist",
    "start": "concurrently -k \"npm:server:*\"",
    "server:products": "nodemon dist/services/products/index.js",
    "server:storefronts": "nodemon dist/services/storefronts/index.js",
    "server:gateway": "wait-on tcp:4001 && wait-on tcp:4002 && nodemon dist/index.js"
  },
  "dependencies": {
    "@graphql-tools/schema": "^7.0.0",
    "@graphql-tools/stitch": "^7.0.4",
    "@graphql-tools/wrap": "^7.0.1",
    "cross-fetch": "^3.0.6",
    "express": "^4.17.1",
    "express-graphql": "^0.12.0",
    "graphql": "^15.4.0",
    "wait-on": "^5.2.0",
    "concurrently": "^5.3.0",
    "nodemon": "^2.0.6"
  },
  "devDependencies": {
    "@types/node": "^14.14.20",
    "@types/express": "^4.17.9",
    "typescript": "^4.1.3",
    "copyfiles": "^2.4.1"
  }
}
```

running `npm run start` will trigger it all.
Of course, the example above does a little more - I prefer  typed language, so I converter the code to typescript.

**Comment by gmac** [comment]
TIL. That’s way nicer than some of my hacks in other examples. Will try that out and absolutely get that into play. Thanks!!

**Comment by gmac** [comment]
@orefalo — correct me if I’m wrong, but wait-on will only control the initial startup, no? Subsequent nodemon restarts will still be subject to race failures because the entire process did not restart, just the app?

**Comment by orefalo** [comment]
If I get your question right:
`wait-on` doesn't change any of the nodemon's behaviors. It basically waits for a socket to be listening and returns _true_.

If I recall nodemon restarts the node process where ts-node-dev (that's for the typescript ecosystem) doesn't. I am not bought on the latest.

**Comment by gmac** [comment]
Multiple apps may be restarted at once by nodemon – changes to a subservice will restart itself and the gateway; at which time, the gateway needs to wait on all processes each time it is restarted (not just the first time it is launched from the command line). Unless I'm overlooking something?

Either way, I don't think it's a huge deal given that this is really just some convenience sprinkled over inherently synthetic examples. TBH, I just ripped off the basic setup from the [federation demo](https://github.com/apollographql/federation-demo/blob/master/package.json) :-P

**Comment by orefalo** [comment]
Well didn't know! ;-)
