### ISSUE TITLE
Proxied services occasionally don't respond

### ISSUE THREAD

**Issue by assafwalkme** [gmac/schema-stitching-demos#27]
Running the `federation-services` examples, occasionally the gateway doesn't respond. After some debugging, it seems that the underlying services don't respond to the fetch operation. This is not deterministic. it can work perfectly for 3 consecutive requests and then timeout. It is also not related to a specific service.

Reproduction is very easy:
1. Clone this repo
2.  Run `federation-services` (npm run start)
3. open the Graphiql interface at `http://localhost:4000/graphql`
4. run the following query:
```
query {
  product(upc: "2") {
    price
  }
  user(id: "1") {
    username
  }
}
```
5. re-run the query consecutively a few times

**Comment by gmac** [comment]
I haven't tried this, but your comment raises an excellent point that is not well documented about the intentions of that example... Stitching makes no guarantees about interoperability with Federation, now or (especially) in the future. I've updated the readme to be more clear about the goals of that example: https://github.com/gmac/schema-stitching-handbook/tree/master/federation-services#federation-services.

All that said, to my knowledge, there's _currently_ nothing fancy about a federation subservice that should prohibit its `_entities` query from being harnessed by a stitching gateway. I do know that [their future roadmap](https://www.youtube.com/watch?v=MvHzOwdLb_o) contains several goodies that further couples subservices with their gateway implementation, so opportunities for stitching to be a generic replacement will only diminish.

That said, I'm not investing very heavily in that example beyond sharing the knowledge and contextualizing its limits.
