### ISSUE TITLE
Remote schema fetching errors

### ISSUE THREAD

**Issue by kamboj652** [gmac/schema-stitching-demos#33]
How do you handle errors when the remote schema is not available?

**Comment by gmac** [comment]
Sorry for the slow reply! As demonstrated in the first example, there's [absolutely nothing fancy behind making remote requests](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/lib/make_remote_executor.js#L11-L19)... you're just wrapping a simple fetch call. Therefore, it's quite easy to make your remote executor provide any tailored GraphQL errors that you'd like based on a returned network status. For example:

```js
if (response.status !== 200) {
  return { errors: [{
    message: "Remote service was unavailable",
    extensions: { code: "REMOTE_UNAVAILABLE" },
  }] };
}
```
