### ISSUE TITLE
Type Transformation in Stitched Schema Example

### ISSUE THREAD

**Issue by ef-mojotrek** [gmac/schema-stitching-demos#38]
Hello, 
The `combining-local-and-remote-schemas` example is not complete. [Here](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/index.js#L16) looks like a typo, the port is already used for `productExecutor` on a previous line. [Here](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/index.js#L16) the transformation on the `Rainforest` type is incomplete since there is no `Rainforest` type in this example. Notice [here](https://github.com/gmac/schema-stitching-handbook/tree/master/combining-local-and-remote-schemas/services) that none of the local services contain a `Rainforest` type.

I am hoping we can build out an example for using the `RenameTypes` and `RenameRootFields` as shown [here](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/index.js#L45) and [here](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/index.js#L46).

Thank you

**Comment by gmac** [comment]
The example most certainly is complete to the extent described in the [tutorial](https://github.com/gmac/schema-stitching-handbook/tree/master/combining-local-and-remote-schemas) and [accompanying video](https://www.youtube.com/watch?v=8-mZqjgIdiI).

- [This](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/index.js#L16) is not a typo; as described in the tutorial, we're pretending that the products service is two different services to demonstrate transforms. The `Rainforest` type is fed by the underlying products service.
- The `Rainforest` type is most certainly complete – have you tried introspecting the gateway schema or browsing its documentation in GraphiQL? It is a _generated type_ built by transforms and serviced by the underlying Product service. We don't necessarily expect to find transformations as source types in the underlying services. Same goes for the generated root field.

All that's to say, this example succinctly demonstrates the use of `RenameTypes` and `RenameRootFields` [as you've indicated](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/index.js#L45-L46). Please leave your biases at the door when seeking reference and pay attention to the surrounding documentation.
